### ISSUE TITLE
the &q about headers.weekDays output if set WeekDayType

### ISSUE THREAD

**Issue by umissthestars** [veccu/react-calendar#85]
## Description
if set WeekDayType = 1
the output of ```headers.weekDays``` like: 
```[
`2021-09-27`, 
`2021-09-28`,
`2021-09-29`, 
`2021-09-30`, 
`2021-10-01`, 
`2021-10-02`, 
`2021-09-26`
]
```
the wrong is ``` "2021-09-26" ```, so do what could i get the correct one
## Current

"2021-09-26"

## Expected

"2021-10-03"

## References

**Comment by JaeYeopHan** [comment]
thanks! i'll check this issue asap (but, personal schedule so busy... sorry)

**Comment by techoi** [comment]
Let me try it.

**Comment by JaeYeopHan** [comment]
@umissthestars could you check this issue in 2.3.3 version? #86 fixed it.
