### ISSUE TITLE
Add incorrect week

### ISSUE THREAD

**Issue by n1kko777** [veccu/react-calendar#97]
Hello! If `defaultWeekStart` is 1, `navigation.toNext` working incorrect in `week` type. I think this happened because the next week starts by default from Sunday, and I should have Monday.

https://github.com/veccu/react-calendar/blob/3735013701b614ba6dcadfbc851cf0409eee5102/src/useCalendar.ts#L108

**Comment by JaeYeopHan** [comment]
thanks! i'll check this issue

**Comment by JaeYeopHan** [comment]
fixed in [v2.3.4](https://github.com/veccu/react-calendar/releases/tag/v2.3.4)
